{% set name = "langchain-google-genai" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_google_genai-{{ version }}.tar.gz
  sha256: c3ac9252cebc77c7887e00487ca531d453965a6088406728b61d3296595c11c7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - pydantic >=2,<3
    - python >=3.9,<4.0
    - langchain-core >=0.3.13,<0.4
    - google-generativeai >=0.8.0,<0.9.0
    - grpcio
  run_constrained:
    - pillow >=10.1.0,<11.0.0

test:
  imports:
    - langchain_google_genai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain-google
  summary: An integration package connecting Google's genai package and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
