{% set name_dev = "langchain-google" %}
{% set name_proj = "genai" %}
{% set name = name_dev + "-" + name_proj %}
{% set alt_name = name.replace('-', '_') %}
{% set version = "2.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ alt_name }}-{{ version }}.tar.gz
    sha256: 04fa7c35902a65036a8f5f91dfdd3c87f926e5d54911113028a86bcbd1e2db00
    folder: pypi
  - url: https://github.com/langchain-ai/{{ name_dev }}/archive/refs/tags/libs/{{ name_proj }}/v{{ version }}.tar.gz
    sha256: c9eab95f4be7dfdb53c0c848de76c48409da4ed4fd0f317e1b6fa2f72f82db34
    folder: gh

build:
  # not supported by upstream
  skip: True  # [py<39]
  script: cd pypi && {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python
    - poetry-core >=1.0.0
    - pip
  run:
    - python
    - filetype >=1.2.0,<2.0.0
    - pydantic >=2,<3
    - langchain-core >=0.3.15,<0.4
    - google-generativeai >=0.8.0,<0.9.0
    - grpcio
  run_constrained:
    - pillow >=10.1.0,<11.0.0

test:
  imports:
    - langchain_google_genai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain-google
  summary: An integration package connecting Google's genai package and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
