{% set name = "langchain-google-genai" %}
{% set version = "1.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langchain_google_genai-{{ version }}.tar.gz
  sha256: 7c964117fa385c490b323ee50ab46907229823d3678b80bfacc8fa0a237fb0b9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9,<4.0
    - langchain-core >=0.2.2,<0.3
    - google-generativeai >=0.5.2,<0.6.0
    - grpcio
  run_constrained:
    - pillow >=10.1.0,<11.0.0

test:
  imports:
    - langchain_google_genai
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/langchain-ai/langchain-google
  summary: An integration package connecting Google's genai package and LangChain
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
